### API : 회원가입
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "loginId": "hjaedeok",
  "password" : "test!1234",
  "name": "deok",
  "birthDate": "2025-09-30",
  "gender": "MAN",
  "email": "hello@gmail.com"
}

### API : 로그인
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
"loginId": "hjaedeok",
"password" : "test!1234"
}